namespace RailworksForge.Core;

public enum BlueprintType
{
    Engine,
    Wagon,
    Tender,
    TextureSet,
    Reskin,
    Spotlight,
    Bogey,
    Scenery,
    AnimatedScenery,
    EngineSim,
    CouplingType,
    HeadOutCamera,
    CabCamera,
    PointLight,
    Emitter,
    HeadLight,
    ProceduralShape,
    Sound,
    CabOcclusion,
    AnimProceduralScenery,
    InputMapper,
    Driver,
    EngineSimSubSystem,
    Fireman,
    EditorShape,
    AnalogClock,
    DigitalClock,
}
