using RailworksForge.Core.Types;

namespace RailworksForge.Core.Models.Examples;

public static partial class Example
{
    public static List<Scenario> Scenarios =>
    [
        new()
        {
            Id = "ea33df44-8d47-428b-892f-8ffe3641cbbe",
            Route = Route,
            Name = "[RS] 92044 - 1M16 20:45 Inverness - London Euston (2019)" ,
            Description = "Following significant delays due to OHLE issues around Lockerbie and then a points failure north of Carlisle, 1M16 the up Highlander sleeper service is running over two hours late on arrival at Preston! You will now oversee the beds as far as Stafford this morning with one drop off station call at Crewe. Control have requested the best run possible but with several faster passenger trains now running, there's no guarantees. Year: 2019.",
            Briefing = "Morning driver, what a night this has been for the beds! Damage to the OHLE and then a points failure north of Carlisle have resulted in 1M16 now running over two hours late. You have just taken over control of 92044 here at Preston and you will now work this heavily delayed Highlander service as far as Stafford making a station call at Crewe on route. Your maximum permitted speed this morning is 87mph, enjoy.",
            StartLocation = "Preston Platform 3",
            Locomotive = "Class 92 Railfreight",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/ea33df44-8d47-428b-892f-8ffe3641cbbe",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/ea33df44-8d47-428b-892f-8ffe3641cbbe/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "c06c8c17-0bda-4a8c-9bd9-3c957084c07a",
            Route = Route,
            Name = "1A97 19:25 Warrington RMT - Willesden PRDC 2020" ,
            Description = "<supply description>",
            Briefing = "Hello Driver Please read as there has been a change to your Route Tonight . Owing to a landslip in the Madeley Area, the West Coast Main Line is closed for about 2-3 hours this evening. As a result, all WCML Traffic is being squeezed through the Stoke Line,  UID 96482, identity 187D\nTSC 56030020\nSTP schedule\n16th June 2020 only\nPost Office Controlled Parcels\nGreat Britain (Network Rail, VSTP)\nTrain obfuscated. More info here.\nPathed as Electric locomotive, trailing load 325 tonnes\nPlanned for 100mph max\nTRUST ID 35283C2Y10\nActivated 16/06/2020 11:57",
            StartLocation = "Barry Price",
            Locomotive = "Class 325 Royal Mail Revised",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/c06c8c17-0bda-4a8c-9bd9-3c957084c07a",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/c06c8c17-0bda-4a8c-9bd9-3c957084c07a/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "e53f80b1-2769-42e1-a087-19be19bb0214",
            Route = Route,
            Name = "Free  scenario",
            Description = "<supply description>",  Briefing = "<supply briefing>",
            StartLocation = "",
            Locomotive = "",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/e53f80b1-2769-42e1-a087-19be19bb0214",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/e53f80b1-2769-42e1-a087-19be19bb0214/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.FreeRoam,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "456d3787-359d-4d0a-b339-784efff85b97",
        Route = Route,
            Name = "MNWPH3-01: 1S36: 0615 Birmingham New Street to Edinburgh Waverley" ,
            Description = "On a crisp morning, work 1S36: 06:15 Birmingham New Street - Edinburgh as far as Preston.\n",
            Briefing = "Good morning driver, welcome to 390132. Your duty this morning is to work 1S36, the 06:15 Avanti Service to Edinburgh Waverley, as far as Preston. You will be calling at, Sandwell & Dudley, Wolverhampton, Crewe, Warrington Bank Quay, Wigan North Western and Preston. So far there have been no issues reported this morning, however LNWR's 1F30 to Liverpool has left 10 minutes late due to a door fault. This shouldnt slow you down too much however. Prepare your train, release your doors and enjoy the run.",
            StartLocation = "",
            Locomotive = "Class 390 'Pendolino'",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/456d3787-359d-4d0a-b339-784efff85b97",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/456d3787-359d-4d0a-b339-784efff85b97/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "9bedaff9-4956-444b-aac9-d1520f5d2de7",
            Route = Route,
            Name = "MNWPH3-01: 1S36: 0615 Birmingham New Street to Edinburgh Waverley (Default 325)",
            Description = "On a crisp morning, work 1S36: 06:15 Birmingham New Street - Edinburgh as far as Preston.\n",
            Briefing = "Good morning driver, welcome to 390132. Your duty this morning is to work 1S36, the 06:15 Avanti Service to Edinburgh Waverley, as far as Preston. You will be calling at, Sandwell & Dudley, Wolverhampton, Crewe, Warrington Bank Quay, Wigan North Western and Preston. So far there have been no issues reported this morning, however LNWR's 1F30 to Liverpool has left 10 minutes late due to a door fault. This shouldnt slow you down too much however. Prepare your train, release your doors and enjoy the run.",
            StartLocation = "",
            Locomotive = "Class 390 'Pendolino'",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/9bedaff9-4956-444b-aac9-d1520f5d2de7",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/9bedaff9-4956-444b-aac9-d1520f5d2de7/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "69e79fc7-c229-4ab1-8d16-042fd3533c53",
            Route = Route,
            Name = "MNWPH3-02: 9M52: 08:52 Edinburgh Waverley - London Euston",
            Description = "Work an early morning Avanti West Coast 9M25: 08:52 Edinburgh Waverley - London Euston as far as Birmingham New Street. You have 11 Car 390131",
            Briefing = "Good morning driver, this service has so far had a very good run south, lets hope that can continue. Prepare your train and prepare for an 11:15 departure out of Preston. You would usually have a 10 car Voyager for this run, however, the unit developed a category A Fault at Polamdie this morning. You have therefore been given this 11 car pendolino that was spare. Traffic isnt too bad this morning so you should have a good run into Birmingham. You will be calling at Wigan North Western, Warrington Bank Quay, Crewe, Wolverhampton, Sandwell & Dudley and finally Birmingham New Street where you will be relieved. Enjoy the run",
            StartLocation = "",
            Locomotive = "Class 390 'Pendolino'",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/69e79fc7-c229-4ab1-8d16-042fd3533c53",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/69e79fc7-c229-4ab1-8d16-042fd3533c53/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "f9f78911-3818-46ac-a77a-324321c2bc83",
            Route = Route,
            Name = "MNWPH3-02: 9M52: 08:52 Edinburgh Waverley - London Euston (Default 325)",
            Description = "Work an early morning Avanti West Coast 9M25: 08:52 Edinburgh Waverley - London Euston as far as Birmingham New Street. You have 11 Car 390131",
            Briefing = "Good morning driver, this service has so far had a very good run south, lets hope that can continue. Prepare your train and prepare for an 11:15 departure out of Preston. You would usually have a 10 car Voyager for this run, however, the unit developed a category A Fault at Polamdie this morning. You have therefore been given this 11 car pendolino that was spare. Traffic isnt too bad this morning so you should have a good run into Birmingham. You will be calling at Wigan North Western, Warrington Bank Quay, Crewe, Wolverhampton, Sandwell & Dudley and finally Birmingham New Street where you will be relieved. Enjoy the run",
            StartLocation = "",
            Locomotive = "Class 390 'Pendolino'",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/f9f78911-3818-46ac-a77a-324321c2bc83",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/f9f78911-3818-46ac-a77a-324321c2bc83/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
        new()
        {
            Id = "0355f6a3-ffb2-4a48-8001-4125a8253dfc",
            Route = Route,
            Name = "MNWPH3-03: 1L69 0833 Liverpool Lime Street to Birmingham New Street",
            Description = "On a bright summers morning, work 1L69: 08:33 Liverpool Lime Street to Birmingham in its entirety.",
            Briefing = "Hello driver, set up your train and prepare for an 08:33 departure out of Liverpool Lime Street. You will be working this service all the way to Birmingham New Street calling at, Liverpool South Parkway, Runcorn, Acton Bridge, Hartford, Winsford, Crewe, Stafford, Wolverhampton, Coesley, Sandwell & Dudley, Smethwick Galton Bridge and Birmingham New Street. Traffic is a little heavy this morning but it shouldnt be too hard to keep time. Enjoy the run\n",
            StartLocation = "",
            Locomotive = "Class 350 Ex-London Midland (LNWR) AP",
            DirectoryPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/0355f6a3-ffb2-4a48-8001-4125a8253dfc",
            ScenarioPropertiesPath = "/cache/SteamLibrary/steamapps/common/RailWorks/Content/Routes/045911ae-114c-4dfc-8382-4505d0491555/Scenarios/0355f6a3-ffb2-4a48-8001-4125a8253dfc/ScenarioProperties.xml",
            Consists = [],
            PackagingType = PackagingType.Unpacked,
            ScenarioClass = ScenarioClass.Standard,
            AssetPath = AssetPath.Empty,
        },
    ];
}
